apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: mirror-devn00b
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
          - image: buddyspencer/gickup
            command:
            - /gickup/gickup
            args:
            - /config/conf.yaml
            resources:
              limits:
                cpu: 8000m
                memory: 32Gi
            volumeMounts:
            - name: conf-yaml
              mountPath: /config
          maxRetries: 3
          timeoutSeconds: '1800'
          volumes:
          - name: conf-yaml
            secret:
              secretName: gickup-conf
              items:
              - key: latest
                path: conf.yaml
